# Generated by Django 5.2.4 on 2025-07-14 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0003_alter_student_email_membership'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='dorm_location',
            new_name='home_location',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='dorm_name',
            new_name='home_name',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='guardian_name',
            new_name='parents_name',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='guardian_phone',
            new_name='parents_phone',
        ),
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='student_photos'),
        ),
    ]
