# Generated by Django 5.2.4 on 2025-07-14 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0004_rename_dorm_location_student_home_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='level',
            field=models.CharField(choices=[('maba', 'Mahasiswa Baru'), ('regular', 'Reguler')], default='regular', max_length=10),
        ),
        migrations.DeleteModel(
            name='Membership',
        ),
    ]
