# Generated by Django 5.2.4 on 2025-07-14 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0006_student_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='is_verified',
        ),
    ]
