# Generated by Django 5.2.4 on 2025-08-04 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0007_remove_student_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='level',
            field=models.CharField(choices=[('maba', 'Mahasiswa Baru'), ('regular', 'Reguler'), ('alumni', 'Alumni')], default='regular', max_length=10),
        ),
    ]
