# Generated by Django 5.2.4 on 2025-08-11 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0008_alter_student_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='arts',
            field=models.TextField(blank=True, null=True, verbose_name='Minat/Bakat Kesenian'),
        ),
        migrations.AddField(
            model_name='student',
            name='arts_achievements',
            field=models.TextField(blank=True, null=True, verbose_name='Prestasi Kesenian'),
        ),
        migrations.AddField(
            model_name='student',
            name='illness_history',
            field=models.TextField(blank=True, null=True, verbose_name='Riwayat Penyakit'),
        ),
        migrations.AddField(
            model_name='student',
            name='illness_status',
            field=models.CharField(blank=True, choices=[('sembuh', 'Sembuh'), ('belum sembuh', 'Belum Sembuh')], max_length=20, null=True, verbose_name='Status Penyakit'),
        ),
        migrations.AddField(
            model_name='student',
            name='literacy',
            field=models.TextField(blank=True, null=True, verbose_name='Minat/Bakat Literasi'),
        ),
        migrations.AddField(
            model_name='student',
            name='literacy_achievements',
            field=models.TextField(blank=True, null=True, verbose_name='Prestasi Literasi'),
        ),
        migrations.AddField(
            model_name='student',
            name='media',
            field=models.TextField(blank=True, null=True, verbose_name='Minat/Bakat Media'),
        ),
        migrations.AddField(
            model_name='student',
            name='media_achievements',
            field=models.TextField(blank=True, null=True, verbose_name='Prestasi Media'),
        ),
        migrations.AddField(
            model_name='student',
            name='mtq',
            field=models.TextField(blank=True, null=True, verbose_name='Minat/Bakat MTQ'),
        ),
        migrations.AddField(
            model_name='student',
            name='mtq_achievements',
            field=models.TextField(blank=True, null=True, verbose_name='Prestasi MTQ'),
        ),
        migrations.AddField(
            model_name='student',
            name='organizational_history',
            field=models.TextField(blank=True, null=True, verbose_name='Riwayat Organisasi'),
        ),
        migrations.AddField(
            model_name='student',
            name='science',
            field=models.TextField(blank=True, null=True, verbose_name='Minat/Bakat Keilmuan'),
        ),
        migrations.AddField(
            model_name='student',
            name='science_achievements',
            field=models.TextField(blank=True, null=True, verbose_name='Prestasi Keilmuan'),
        ),
        migrations.AddField(
            model_name='student',
            name='sports',
            field=models.TextField(blank=True, null=True, verbose_name='Minat/Bakat Olahraga'),
        ),
        migrations.AddField(
            model_name='student',
            name='sports_achievements',
            field=models.TextField(blank=True, null=True, verbose_name='Prestasi Olahraga'),
        ),
    ]
