# Generated by Django 5.2.4 on 2025-08-11 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0009_student_arts_student_arts_achievements_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='arts',
        ),
        migrations.RemoveField(
            model_name='student',
            name='arts_achievements',
        ),
        migrations.RemoveField(
            model_name='student',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='student',
            name='education_funding',
        ),
        migrations.RemoveField(
            model_name='student',
            name='illness_history',
        ),
        migrations.RemoveField(
            model_name='student',
            name='illness_status',
        ),
        migrations.RemoveField(
            model_name='student',
            name='literacy',
        ),
        migrations.RemoveField(
            model_name='student',
            name='literacy_achievements',
        ),
        migrations.RemoveField(
            model_name='student',
            name='living_cost',
        ),
        migrations.RemoveField(
            model_name='student',
            name='media',
        ),
        migrations.RemoveField(
            model_name='student',
            name='media_achievements',
        ),
        migrations.RemoveField(
            model_name='student',
            name='monthly_income',
        ),
        migrations.RemoveField(
            model_name='student',
            name='mtq',
        ),
        migrations.RemoveField(
            model_name='student',
            name='mtq_achievements',
        ),
        migrations.RemoveField(
            model_name='student',
            name='organizational_history',
        ),
        migrations.RemoveField(
            model_name='student',
            name='parents_phone',
        ),
        migrations.RemoveField(
            model_name='student',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='student',
            name='scholarship_source',
        ),
        migrations.RemoveField(
            model_name='student',
            name='science',
        ),
        migrations.RemoveField(
            model_name='student',
            name='science_achievements',
        ),
        migrations.RemoveField(
            model_name='student',
            name='sports',
        ),
        migrations.RemoveField(
            model_name='student',
            name='sports_achievements',
        ),
        migrations.RemoveField(
            model_name='student',
            name='umdah_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='umdah_phone',
        ),
        migrations.RemoveField(
            model_name='student',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='student',
            name='art_achievement',
            field=models.TextField(blank=True, verbose_name='Prestasi Kesenian'),
        ),
        migrations.AddField(
            model_name='student',
            name='art_interest',
            field=models.CharField(blank=True, max_length=150, verbose_name='Minat Kesenian'),
        ),
        migrations.AddField(
            model_name='student',
            name='disease_history',
            field=models.CharField(blank=True, max_length=255, verbose_name='Riwayat Penyakit'),
        ),
        migrations.AddField(
            model_name='student',
            name='disease_status',
            field=models.CharField(blank=True, choices=[('sembuh', 'Sembuh'), ('belum', 'Belum Sembuh')], max_length=10),
        ),
        migrations.AddField(
            model_name='student',
            name='literacy_achievement',
            field=models.TextField(blank=True, verbose_name='Prestasi Literasi'),
        ),
        migrations.AddField(
            model_name='student',
            name='literacy_interest',
            field=models.CharField(blank=True, max_length=150, verbose_name='Minat Literasi'),
        ),
        migrations.AddField(
            model_name='student',
            name='media_achievement',
            field=models.TextField(blank=True, verbose_name='Prestasi Media'),
        ),
        migrations.AddField(
            model_name='student',
            name='media_interest',
            field=models.CharField(blank=True, max_length=150, verbose_name='Minat Media'),
        ),
        migrations.AddField(
            model_name='student',
            name='mtq_achievement',
            field=models.TextField(blank=True, verbose_name='Prestasi MTQ'),
        ),
        migrations.AddField(
            model_name='student',
            name='mtq_interest',
            field=models.CharField(blank=True, max_length=150, verbose_name='Minat MTQ'),
        ),
        migrations.AddField(
            model_name='student',
            name='organization_history',
            field=models.TextField(blank=True, verbose_name='Riwayat Organisasi'),
        ),
        migrations.AddField(
            model_name='student',
            name='science_achievement',
            field=models.TextField(blank=True, verbose_name='Prestasi Keilmuan'),
        ),
        migrations.AddField(
            model_name='student',
            name='science_interest',
            field=models.CharField(blank=True, max_length=150, verbose_name='Minat Keilmuan'),
        ),
        migrations.AddField(
            model_name='student',
            name='sport_achievement',
            field=models.TextField(blank=True, verbose_name='Prestasi Olahraga'),
        ),
        migrations.AddField(
            model_name='student',
            name='sport_interest',
            field=models.CharField(blank=True, max_length=150, verbose_name='Minat Olahraga'),
        ),
        migrations.AlterField(
            model_name='student',
            name='level',
            field=models.CharField(choices=[('maba', 'Mahasiswa Baru'), ('regular', 'Reguler'), ('alumni', 'Alumni')], default='maba', max_length=20),
        ),
    ]
