# Generated by Django 5.2.4 on 2025-08-17 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0010_remove_student_arts_remove_student_arts_achievements_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='degree_level',
            field=models.CharField(choices=[('D3', 'D3'), ('S1', 'S1'), ('S2', 'S2'), ('S3', 'S3')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='full_name',
            field=models.CharField(db_index=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='student',
            name='level',
            field=models.CharField(choices=[('maba', 'Mahasiswa Baru'), ('regular', 'Reguler'), ('alumni', 'Alumni')], db_index=True, default='maba', max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='marital_status',
            field=models.CharField(choices=[('single', 'Single'), ('married', 'Married')], db_index=True, max_length=20),
        ),
    ]
