# Generated by Django 5.2.4 on 2025-08-17 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0011_alter_student_degree_level_alter_student_full_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_draft',
            field=models.BooleanField(default=False),
        ),
    ]
