# Generated by Django 5.2.4 on 2025-08-20 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0014_add_financial_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='degree_level',
            field=models.CharField(choices=[('S1', 'S1'), ('S2', 'S2'), ('S3', 'S3')], db_index=True, max_length=20),
        ),
    ]
