# Generated by Django 5.2.4 on 2025-08-20 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0015_alter_student_degree_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='parents_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Nomor Telepon Orang Tua'),
        ),
    ]
