# Generated by Django 5.2.4 on 2025-11-08 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0016_student_parents_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='email',
        ),
        migrations.RemoveField(
            model_name='student',
            name='full_name',
        ),
    ]
