# Generated by Django 5.2.4 on 2025-11-18 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0017_remove_student_email_remove_student_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='guardian_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Nama Wali/Umdah'),
        ),
        migrations.AddField(
            model_name='student',
            name='guardian_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Nomor HP Wali/Umdah'),
        ),
        migrations.AddField(
            model_name='student',
            name='photo_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='Link Foto (Google Drive)'),
        ),
    ]
