# Generated by Django 5.2.4 on 2025-11-18 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0018_student_guardian_name_student_guardian_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='degree_level',
            field=models.CharField(choices=[('mahad', 'Mahad'), ('DL', 'Daurah Lughah'), ('S1', 'S1'), ('S2', 'S2'), ('S3', 'S3')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='home_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='student',
            name='parents_phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='Nomor Telepon Orang Tua'),
        ),
    ]
